-- CreateTable
CREATE TABLE "Kuva" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "teksti" TEXT NOT NULL,
    "tiedosto" TEXT NOT NULL,
    "aika" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);
